const music_data = [
    {
        id: 0,
        song_path: '../../src/musics/ArcticMonkeys-505.mp3',
        song_poster: '../../src/music_posters/poster-arctic-monkeys.jpeg',
        singer: 'Arctic Monkeys',
        song_name: 'Arctic Monkeys - 505',
        song_duration: 4.09,
        song_release_date: '2012',
    }, {
        id: 1,
        song_path: '../../src/musics/ArcticMonkeys-DoIWannaKnow.mp3',
        song_poster: '../../src/music_posters/poster-arctic-monkeys.jpeg',        singer: 'Arctic Monkeys',
        song_name: 'Do I Wanna Know',
        song_duration: 4.25,
        song_release_date: '',
    }, {
        id: 2,
        song_path: '../../src/musics/ArcticMonkeys-IWannaBeYours.mp3',
        song_poster: '../../src/music_posters/poster-arctic-monkeys.jpeg',
        singer: 'Arctic Monkeys',
        song_name: 'I Wanna Be Yours',
        song_duration: 3.04,
        song_release_date: '',
    }, {
        id: 3,
        song_path: '../../src/musics/ArcticMonkeys-RUMine.mp3',
        song_poster: '../../src/music_posters/poster-arctic-monkeys.jpeg',        singer: 'Arctic Monkeys',
        song_name: 'R U Mine',
        song_duration: 3.44,
        song_release_date: '',
    }, {
        id: 4,
        song_path: '../../src/musics/BillieEilish-badguy.mp3',
        song_poster: '../../src/music_posters/Billie-eilish-poster.jpg',
        singer: 'Billie Eilish',
        song_name: 'bad guy',
        song_duration: 3.26,
        song_release_date: '',
    }, {
        id: 5,
        song_path: "../../src/musics/BillieEilish-lovely(withKhalid).mp3",
        song_poster: '../../src/music_posters/Billie-eilish-poster.jpg',
        singer: 'Billie Eilish',
        song_name: 'lovely (with Khalid)',
        song_duration: '3.20',
        song_release_date: '',
    }, {
        id: 6,
        song_path: '../../src/musics/BillieEilish-whenthepartysover.mp3',
        song_poster: '../../src/music_posters/Billie-eilish-poster.jpg',
        singer: 'Billie Eilish',
        song_name: 'when the partys over',
        song_duration: 3.14,
        song_release_date: '',
    }, {
        id: 7,
        song_path: '../../src/musics/Madonna-LaIslaBonita.mp3',
        song_poster: '../../src/music_posters/madonna-poster.webp',
        singer: 'Madonna',
        song_name: 'La Isla Bonita',
        song_duration: 4.01,
        song_release_date: '',
    }, {
        id: 8,
        song_path: '../../src/musics/ModernTalking-CheriCheriLady.mp3',
        song_poster: '../../src/music_posters/modern-talking-poster.jpg',
        singer: 'Modern Talking',
        song_name: 'Cheri Cheri Lady',
        song_duration: 3.17,
        song_release_date: '',
    }, {
        id: 9,
        song_path: '../../src/musics/Otilia-Prisonera(TwinsparksRemix).mp3',
        song_poster: '../../src/music_posters/Otilia-poster.webp',
        singer: 'Otilia',
        song_name: 'Prisonera (Twinsparks Remix)',
        song_duration: 2.58,
        song_release_date: '',
    }, {
        id: 10,
        song_path: '../../src/musics/Otilia-SweetDreams(RobberRemix).mp3',
        song_poster: '../../src/music_posters/Otilia-poster.webp',
        singer: 'Otilia',
        song_name: 'Sweet Dreams (RobberRemix)',
        song_duration: 2.45,
        song_release_date: '',
    }, {
        id: 11,
        song_path: '../../src/musics/Rihanna-Diamonds.mp3',
        song_poster: '../../src/music_posters/Rihanna-poster.png',
        singer: 'Rihanna',
        song_name: 'Diamonds',
        song_duration: 4.42,
        song_release_date: '',
    }
]

export { music_data };
